name: lapalma-earthquakes
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - pandas
  - scipy
  - seaborn
  - altair
  - plotly
  - jupyterlab>=4.0.0
  - jupyterlab-myst>=2.0.0
  - pip
  - pip:
    - climada
